#!/bin/bash
####
# Sometimes peda exploit framework can be annoying this script allow 
# easly to return to normal gdb (i.e. in case of system development)
#
# Usage: en_peda [0-disable|1-..enable]
####

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 [0|1] enable|disable peda gdb framework" >&2
  exit 1
fi

re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: Not a uns binary number" >&2; exit 1
fi

if [ $1 -eq 0 ]; then
   echo "Disable Peda";
   sed '/peda/d' ~/.gdbinit > ~/.gdbinit
   exit;
else
   echo "Enable Peda"
   echo "source ~/peda/peda.py" >> ~/.gdbinit
   exit;
fi
